
// 这个文件是生成的，请不要手动修改
import { FC, lazy, LazyExoticComponent, ComponentType } from 'react'; //

export type TC = LazyExoticComponent<ComponentType> | FC
export const routesMeta = [
  "/config-table/index.tsx",
  "/config-table/list/index.tsx",
  "/config-table/panel/index.tsx",
  "/data-report/admission-visit/index.tsx",
  "/data-report/first-visit/index.tsx",
  "/data-report/second-visit/index.tsx",
  "/deliver-management-v2/index.tsx",
  "/fetal-custom-analyse/index.tsx",
  "/fetal-custom-analyse-entry/index.tsx",
  "/fetal-custom-analyse-list/index.tsx",
  "/follow-up/questionnaire3/index.tsx",
  "/follow-up/test/index.tsx",
  "/gynecological-diseases/test/index.tsx",
  "/gynecological-diseases/women/edit/index.tsx",
  "/gynecological-diseases/women/index.tsx",
  "/gynecological-diseases/women/list/index.tsx",
  "/gynecological-diseases/women/women-exam-records/add/index.tsx",
  "/gynecological-diseases/women/women-exam-records/edit/index.tsx",
  "/gynecological-diseases/women/women-exam-records/form_config/index.tsx",
  "/gynecological-diseases/women/women-exam-records/index.tsx",
  "/prenatal-visit/physical-sign/list/index.tsx",
  "/prenatal-visit/pregnancy/add/index.tsx",
  "/prenatal-visit/pregnancy/check/index.tsx",
  "/prenatal-visit/pregnancy/list/index.tsx",
  "/prenatal-visit/pregnancy/nurse-end/index.tsx",
  "/system/configuration/index.tsx",
  "/system/request-log/index.tsx",
  "/system/role/index.tsx",
  "/system/user/index.tsx",
  "/system-config/index.tsx",
  "/test/index.tsx"
]
export const routesData = {
    "/config-table":lazy(() => import("../pages/config-table/index")),
    "/config-table/list":lazy(() => import("../pages/config-table/list/index")),
    "/config-table/panel":lazy(() => import("../pages/config-table/panel/index")),
    "/data-report/admission-visit":lazy(() => import("../pages/data-report/admission-visit/index")),
    "/data-report/first-visit":lazy(() => import("../pages/data-report/first-visit/index")),
    "/data-report/second-visit":lazy(() => import("../pages/data-report/second-visit/index")),
    "/deliver-management-v2":lazy(() => import("../pages/deliver-management-v2/index")),
    "/fetal-custom-analyse":lazy(() => import("../pages/fetal-custom-analyse/index")),
    "/fetal-custom-analyse-entry":lazy(() => import("../pages/fetal-custom-analyse-entry/index")),
    "/fetal-custom-analyse-list":lazy(() => import("../pages/fetal-custom-analyse-list/index")),
    "/follow-up/questionnaire3":lazy(() => import("../pages/follow-up/questionnaire3/index")),
    "/follow-up/test":lazy(() => import("../pages/follow-up/test/index")),
    "/gynecological-diseases/test":lazy(() => import("../pages/gynecological-diseases/test/index")),
    "/gynecological-diseases/women/edit":lazy(() => import("../pages/gynecological-diseases/women/edit/index")),
    "/gynecological-diseases/women":lazy(() => import("../pages/gynecological-diseases/women/index")),
    "/gynecological-diseases/women/list":lazy(() => import("../pages/gynecological-diseases/women/list/index")),
    "/gynecological-diseases/women/women-exam-records/add":lazy(() => import("../pages/gynecological-diseases/women/women-exam-records/add/index")),
    "/gynecological-diseases/women/women-exam-records/edit":lazy(() => import("../pages/gynecological-diseases/women/women-exam-records/edit/index")),
    "/gynecological-diseases/women/women-exam-records/form_config":lazy(() => import("../pages/gynecological-diseases/women/women-exam-records/form_config/index")),
    "/gynecological-diseases/women/women-exam-records":lazy(() => import("../pages/gynecological-diseases/women/women-exam-records/index")),
    "/prenatal-visit/physical-sign/list":lazy(() => import("../pages/prenatal-visit/physical-sign/list/index")),
    "/prenatal-visit/pregnancy/add":lazy(() => import("../pages/prenatal-visit/pregnancy/add/index")),
    "/prenatal-visit/pregnancy/check":lazy(() => import("../pages/prenatal-visit/pregnancy/check/index")),
    "/prenatal-visit/pregnancy/list":lazy(() => import("../pages/prenatal-visit/pregnancy/list/index")),
    "/prenatal-visit/pregnancy/nurse-end":lazy(() => import("../pages/prenatal-visit/pregnancy/nurse-end/index")),
    "/system/configuration":lazy(() => import("../pages/system/configuration/index")),
    "/system/request-log":lazy(() => import("../pages/system/request-log/index")),
    "/system/role":lazy(() => import("../pages/system/role/index")),
    "/system/user":lazy(() => import("../pages/system/user/index")),
    "/system-config":lazy(() => import("../pages/system-config/index")),
    "/test":lazy(() => import("../pages/test/index")),
}