export interface IMchc_ThalassemiaFollowUp {
    "adeletions": "",
    "adeletionsHusband": "",
    "advice": "",
    "age": 0,
    "bdeletions": "",
    "bdeletionsHusband": "",
    "bmutant": "",
    "bmutantHusband": "",
    "department": "",
    "husbandName": "",
    "husbandOutpatientNo": "",
    "husbandTelephone": "",
    "id": 0,
    "name": "",
    "outpatientNo": "",
    "pregnacyId": 0,
    "sampleNo": "",
    "sex": "",
    "specimenDate": "",
    "state": 0,
    "submissionTime": "",
    "telephone": ""
}