import { APP_CONFIG } from '../../../utils/constants';

// 胎儿囊液穿刺
export const cystocentesisColumns = [
  {
    dataIndex: 'name',
    title: '测量值',
    align: 'center',
    editable: false,
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'leftPleuralEffusion',
    title: '左胸腔积液(mm)',
    align: 'center',
    editable: true,
    inputType: 'input',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'rightPleuralEffusion',
    title: '右胸腔积液(mm)',
    align: 'center',
    editable: true,
    inputType: 'input',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'ascites',
    title: '腹水(mm)',
    align: 'center',
    editable: true,
    inputType: 'input',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'hygromata',
    title: '囊肿',
    align: 'center',
    editable: true,
    inputType: 'input',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'note',
    title: '备注',
    align: 'center',
    editable: true,
    inputType: 'input',
    width: 300,
  },
];

// 宫内输血血流
export const bloodFlowsColumns = [
  {
    dataIndex: 'name',
    title: '',
    align: 'center',
    editable: false,
    width: 120,
  },
  {
    dataIndex: 'checkDate',
    title: '日期',
    align: 'center',
    editable: true,
    inputType: 'single_date_picker',
    width: 120,
  },
  {
    dataIndex: 'ua',
    title: 'UA',
    align: 'center',
    children: [
      {
        dataIndex: 'uaEdf',
        title: 'EDF',
        align: 'center',
        editable: true,
        width: 80,
      },
      {
        dataIndex: 'uaPi',
        title: 'PI',
        align: 'center',
        editable: true,
        width: 80,
      },
      {
        dataIndex: 'uaRi',
        title: 'RI',
        align: 'center',
        editable: true,
        width: 80,
      },
      {
        dataIndex: 'uaSdratio',
        title: 'S/D',
        align: 'center',
        editable: true,
        width: 80,
      },
    ],
  },
  {
    dataIndex: 'dv',
    title: 'DV',
    align: 'center',
    editable: true,
    width: 80,
  },
  {
    dataIndex: 'mca',
    title: 'MCA',
    align: 'center',
    width: 80,
    children: [
      {
        dataIndex: 'mcaPsv',
        title: 'PSV(cm/s)',
        align: 'center',
        inputType: 'input',
        editable: true,
        width: 80,
      },
      {
        dataIndex: 'momPsv',
        title: 'PSV(mom)',
        align: 'center',
        inputType: 'input',
        editable: true,
        width: 80,
      },
      {
        dataIndex: 'mcaPi',
        title: 'PI',
        align: 'center',
        inputType: 'input',
        editable: true,
        width: 80,
      },
      {
        dataIndex: 'mcaRi',
        title: 'RI',
        align: 'center',
        editable: true,
        inputType: 'input',
        width: 80,
      },
      {
        dataIndex: 'mcaSdratio',
        title: 'S/D',
        align: 'center',
        editable: true,
        width: 200,
      },
    ],
  },
];

// 宫内输血血像
export const hemogramExamColumns = [
  {
    dataIndex: 'name',
    title: '',
    align: 'center',
    editable: false,
    width: 120,
  },
  {
    dataIndex: 'wbc',
    title: 'WBC(x10⁹/L)',
    align: 'center',
    editable: true,
    width: 100,
  },
  {
    dataIndex: 'rbc',
    title: 'RBC(x10¹²/L)',
    align: 'center',
    editable: true,
    width: 100,
  },
  {
    dataIndex: 'hgb',
    title: 'HGB(g/L)',
    align: 'center',
    editable: true,
    width: 100,
  },
  {
    dataIndex: 'hct',
    title: 'HCT',
    align: 'center',
    editable: true,
    width: 100,
  },
  {
    dataIndex: 'plt',
    title: 'PLT(x10⁹/L)',
    align: 'center',
    editable: true,
    width: 100,
  },
  {
    dataIndex: 'ret',
    title: '网织红(%)',
    align: 'center',
    editable: true,
    width: 100,
  },
  {
    dataIndex: 'nrbc',
    title: '有核红(x10⁹/L)',
    align: 'center',
    editable: true,
    width: 100,
  },
  {
    dataIndex: 'bilirubin',
    title: '胆红素(mmo/L)',
    align: 'center',
    editable: true,
    width: 100,
  },
  {
    dataIndex: 'coombs',
    title: "Coomb's",
    align: 'center',
    editable: true,
    width: 100,
  },
];

export const tableColumns = [
  {
    dataIndex: 'object',
    editable: true,
    align: 'center',
    inputType: 'select_with_options_or_input',
    inputProps: {
      options: [
        {
          label: '单胎',
          value: '单胎',
        },
        {
          label: 'F1',
          value: 'F1',
        },
        {
          label: 'F2',
          value: 'F2',
        },
        {
          label: 'F3',
          value: 'F3',
        },
        {
          label: 'F4',
          value: 'F4',
        },
      ],
    },
    title: '穿刺对象',
    width: APP_CONFIG.CELL_WIDTH_LARGE,
  },
  {
    dataIndex: 'punctureTarget',
    editable: true,
    align: 'center',
    inputType: 'select_with_options_or_input',
    inputProps: {
      options: [
        { label: '经腹部', value: '经腹部' },
        { label: '经脐静脉', value: '经脐静脉' },
      ],
    },
    title: '穿刺部位',
    width: APP_CONFIG.CELL_WIDTH_LARGE,
  },
  {
    dataIndex: 'instrument',
    editable: true,
    align: 'center',
    inputType: 'select_with_options_or_input',
    inputProps: {
      options: [
        {
          label: '穿刺针16/18G',
          value: '穿刺针16/18G',
        },
        {
          label: '穿刺针17/19G',
          value: '穿刺针17/19G',
        },
        {
          label: '穿刺针20G',
          value: '穿刺针20G',
        },
        {
          label: '穿刺针21G',
          value: '穿刺针21G',
        },
        {
          label: '活检钳',
          value: '活检钳',
        },
      ],
    },
    title: '器械',
    width: APP_CONFIG.CELL_WIDTH_LARGE,
  },
  {
    dataIndex: 'punctureAmount',
    editable: true,
    align: 'center',
    inputType: 'input',
    title: '进针次数',
    width: APP_CONFIG.CELL_WIDTH_LARGE,
  },
  {
    dataIndex: 'hitAmount',
    editable: true,
    align: 'center',
    inputType: 'input',
    title: '刺中次数',
    width: APP_CONFIG.CELL_WIDTH_LARGE,
  },
  {
    dataIndex: 'placentaEntryNote',
    editable: true,
    align: 'center',
    // inputType: 'input',
    inputType: 'dictionary_select_in_table',
    inputProps: {
      type: 'select',
      mode: 'single',
      boxSpan: 6,
      uniqueKey: 'prenatalDiagnosis.placentaEntry',
    },
    title: '经否胎盘',
    width: APP_CONFIG.CELL_WIDTH_LARGE,
  },
  {
    dataIndex: 'placentaHemorrhageNote',
    editable: true,
    align: 'center',
    inputType: 'select_with_options_or_input',
    inputProps: {
      options: [
        { label: '无', value: '无' },
        { label: '有', value: '有' },
      ],
    },
    title: '胎盘出血',
    width: APP_CONFIG.CELL_WIDTH_LARGE,
  },
  {
    dataIndex: ['invasiveNote', 'umbilicalHemorrhageNote'],
    editable: true,
    align: 'center',
    inputType: 'select_with_options_or_input',
    inputProps: {
      options: [
        { label: '无', value: '无' },
        { label: '有', value: '有' },
      ],
    },
    title: '脐带出血',
    width: APP_CONFIG.CELL_WIDTH_LARGE,
  },
  {
    dataIndex: ['invasiveNote', 'uterusHemorrhageNote'],
    editable: true,
    align: 'center',
    inputType: 'select_with_options_or_input',
    inputProps: {
      options: [
        { label: '无', value: '无' },
        { label: '有', value: '有' },
      ],
    },
    title: '宫壁出血',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: ['invasiveNote', 'cordbloodvolume'],
    editable: true,
    inputType: 'input',
    align: 'center',
    title: '抽脐血量(ml)',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: ['invasiveNote', 'cordbloodcharacter'],
    editable: true,
    align: 'center',
    inputType: 'select_with_options_or_input',
    inputProps: {
      options: [
        { label: '鲜红', value: '鲜红' },
        { label: '暗红', value: '暗红' },
        { label: '混入羊水', value: '混入羊水' },
        { label: '混入母血', value: '混入母血' },
      ],
    },
    title: '脐血性质',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: ['invasiveNote', 'cordhematoma'],
    editable: true,
    align: 'center',
    inputType: 'select_with_options_or_input',
    inputProps: {
      options: [
        { label: '无', value: '无' },
        { label: '有', value: '有' },
      ],
    },
    title: '脐带血肿',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'fetalanaestheticNote',
    editable: true,
    align: 'center',
    inputType: 'input',
    title: '胎儿麻醉药物名',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'dilutionRatioOfFetalAnesthesiaDrugs',
    editable: true,
    align: 'center',
    inputType: 'input_number',
    title: '胎儿麻醉药物稀释倍数',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'fetalanaesthetic',
    editable: true,
    align: 'center',
    inputType: 'input_number',
    title: '胎儿麻醉药量(mg)',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'postFhr',
    editable: true,
    align: 'center',
    inputType: 'input',
    title: '术后胎心率(bpm)',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'fhrdecNote',
    editable: true,
    align: 'center',
    inputType: 'select_with_options_or_input',
    inputProps: {
      options: [
        { label: '无', value: '无' },
        { label: '有', value: '有' },
      ],
    },
    title: '胎心减慢',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'processEvaluationNote',
    editable: true,
    align: 'center',
    // inputType: 'input',
    inputType: 'dictionary_select_in_table',
    inputProps: {
      type: 'select',
      mode: 'single',
      boxSpan: 6,
      uniqueKey: 'prenatalDiagnosis.processEvaluationNote',
    },
    title: '过程评估',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'hct',
    editable: true,
    align: 'center',
    inputType: 'input',
    title: '目标HCT',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'analysisbtvolume',
    editable: true,
    align: 'center',
    inputType: 'input',
    title: '计算输血量(ml)',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'actualbtvolume',
    editable: true,
    align: 'center',
    inputType: 'input',
    title: '实际输血量(ml)',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'btDuration',
    editable: true,
    align: 'center',
    inputType: 'input',
    title: '输血时间(min)',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'btspeed',
    editable: true,
    align: 'center',
    inputType: 'input',
    title: '输血速度(ml/min)',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'recheckHemogram',
    editable: true,
    align: 'center',
    inputType: 'input',
    title: '复查血象',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
  {
    dataIndex: 'otherNote',
    editable: true,
    align: 'center',
    inputType: 'input',
    title: '备注',
    width: APP_CONFIG.CELL_WIDTH_MIDDLE,
  },
];
