
// 这个文件是生成的，请不要手动修改
import { FC, lazy, LazyExoticComponent, ComponentType } from 'react'; //

export type TC = LazyExoticComponent<ComponentType> | FC
export const routesMeta = [
  "/fubao/data-report/breast-cancer/index.tsx",
  "/fubao/data-report/cervical-cancer/index.tsx",
  "/fubao/family-planning/booking-management/index.tsx",
  "/fubao/family-planning/curettage-statistics/index.tsx",
  "/fubao/family-planning/file-management/doctor-desk/index.tsx",
  "/fubao/family-planning/file-management/doctor-desk2/index.tsx",
  "/fubao/family-planning/file-management/index.tsx",
  "/fubao/family-planning/file-management/list/index.tsx",
  "/fubao/family-planning/file-management/nurse-desk/index.tsx",
  "/fubao/family-planning/surgery-management/index.tsx",
  "/fubao/family-planning/surgery-scheduling/index.tsx",
  "/fubao/family-planning/tracing-management/list/index.tsx",
  "/fubao/folic-acid/file-management/add/index.tsx",
  "/fubao/folic-acid/file-management/edit/index.tsx",
  "/fubao/folic-acid/file-management/list/index.tsx",
  "/fubao/gynecological-diseases/adolescent-management/list/index.tsx",
  "/fubao/gynecological-diseases/breast/edit/index.tsx",
  "/fubao/gynecological-diseases/breast/list/index.tsx",
  "/fubao/gynecological-diseases/cervical/edit/index.tsx",
  "/fubao/gynecological-diseases/cervical/list/index.tsx",
  "/fubao/gynecological-diseases/cervical-cancer-report/list/index.tsx",
  "/fubao/gynecological-diseases/hpv-report/list/index.tsx",
  "/fubao/gynecological-diseases/mammary-cancer-report/list/index.tsx",
  "/fubao/gynecological-diseases/menopause-management/list/index.tsx",
  "/fubao/gynecological-diseases/pathological-follow-up/index.tsx",
  "/fubao/gynecological-diseases/pathological-reminder/index.tsx",
  "/fubao/gynecological-diseases/regular-screening/list/index.tsx",
  "/fubao/gynecological-diseases/two-cancers/add/index.tsx",
  "/fubao/gynecological-diseases/two-cancers/edit/index.tsx",
  "/fubao/gynecological-diseases/two-cancers/exam/index.tsx",
  "/fubao/gynecological-diseases/two-cancers/index.tsx",
  "/fubao/pre-pregnancy-care/file-management/add/index.tsx",
  "/fubao/pre-pregnancy-care/file-management/edit/index.tsx",
  "/fubao/pre-pregnancy-care/file-management/index.tsx",
  "/fubao/pre-pregnancy-care/husband/husband-exam/index.tsx",
  "/fubao/pre-pregnancy-care/wife/wife-exam/index.tsx",
  "/fubao/premarital-care/file-management/add/index.tsx",
  "/fubao/premarital-care/file-management/edit/index.tsx",
  "/fubao/premarital-care/file-management/index.tsx",
  "/fubao/premarital-care/husband-v2/husband-exam/index.tsx",
  "/fubao/premarital-care/wife-v2/wife-exam/index.tsx"
]
export const routesData = {
    "/fubao/data-report/breast-cancer":lazy(() => import("../pages/fubao/data-report/breast-cancer/index")),
    "/fubao/data-report/cervical-cancer":lazy(() => import("../pages/fubao/data-report/cervical-cancer/index")),
    "/fubao/family-planning/booking-management":lazy(() => import("../pages/fubao/family-planning/booking-management/index")),
    "/fubao/family-planning/curettage-statistics":lazy(() => import("../pages/fubao/family-planning/curettage-statistics/index")),
    "/fubao/family-planning/file-management/doctor-desk":lazy(() => import("../pages/fubao/family-planning/file-management/doctor-desk/index")),
    "/fubao/family-planning/file-management/doctor-desk2":lazy(() => import("../pages/fubao/family-planning/file-management/doctor-desk2/index")),
    "/fubao/family-planning/file-management":lazy(() => import("../pages/fubao/family-planning/file-management/index")),
    "/fubao/family-planning/file-management/list":lazy(() => import("../pages/fubao/family-planning/file-management/list/index")),
    "/fubao/family-planning/file-management/nurse-desk":lazy(() => import("../pages/fubao/family-planning/file-management/nurse-desk/index")),
    "/fubao/family-planning/surgery-management":lazy(() => import("../pages/fubao/family-planning/surgery-management/index")),
    "/fubao/family-planning/surgery-scheduling":lazy(() => import("../pages/fubao/family-planning/surgery-scheduling/index")),
    "/fubao/family-planning/tracing-management/list":lazy(() => import("../pages/fubao/family-planning/tracing-management/list/index")),
    "/fubao/folic-acid/file-management/add":lazy(() => import("../pages/fubao/folic-acid/file-management/add/index")),
    "/fubao/folic-acid/file-management/edit":lazy(() => import("../pages/fubao/folic-acid/file-management/edit/index")),
    "/fubao/folic-acid/file-management/list":lazy(() => import("../pages/fubao/folic-acid/file-management/list/index")),
    "/fubao/gynecological-diseases/adolescent-management/list":lazy(() => import("../pages/fubao/gynecological-diseases/adolescent-management/list/index")),
    "/fubao/gynecological-diseases/breast/edit":lazy(() => import("../pages/fubao/gynecological-diseases/breast/edit/index")),
    "/fubao/gynecological-diseases/breast/list":lazy(() => import("../pages/fubao/gynecological-diseases/breast/list/index")),
    "/fubao/gynecological-diseases/cervical/edit":lazy(() => import("../pages/fubao/gynecological-diseases/cervical/edit/index")),
    "/fubao/gynecological-diseases/cervical/list":lazy(() => import("../pages/fubao/gynecological-diseases/cervical/list/index")),
    "/fubao/gynecological-diseases/cervical-cancer-report/list":lazy(() => import("../pages/fubao/gynecological-diseases/cervical-cancer-report/list/index")),
    "/fubao/gynecological-diseases/hpv-report/list":lazy(() => import("../pages/fubao/gynecological-diseases/hpv-report/list/index")),
    "/fubao/gynecological-diseases/mammary-cancer-report/list":lazy(() => import("../pages/fubao/gynecological-diseases/mammary-cancer-report/list/index")),
    "/fubao/gynecological-diseases/menopause-management/list":lazy(() => import("../pages/fubao/gynecological-diseases/menopause-management/list/index")),
    "/fubao/gynecological-diseases/pathological-follow-up":lazy(() => import("../pages/fubao/gynecological-diseases/pathological-follow-up/index")),
    "/fubao/gynecological-diseases/pathological-reminder":lazy(() => import("../pages/fubao/gynecological-diseases/pathological-reminder/index")),
    "/fubao/gynecological-diseases/regular-screening/list":lazy(() => import("../pages/fubao/gynecological-diseases/regular-screening/list/index")),
    "/fubao/gynecological-diseases/two-cancers/add":lazy(() => import("../pages/fubao/gynecological-diseases/two-cancers/add/index")),
    "/fubao/gynecological-diseases/two-cancers/edit":lazy(() => import("../pages/fubao/gynecological-diseases/two-cancers/edit/index")),
    "/fubao/gynecological-diseases/two-cancers/exam":lazy(() => import("../pages/fubao/gynecological-diseases/two-cancers/exam/index")),
    "/fubao/gynecological-diseases/two-cancers":lazy(() => import("../pages/fubao/gynecological-diseases/two-cancers/index")),
    "/fubao/pre-pregnancy-care/file-management/add":lazy(() => import("../pages/fubao/pre-pregnancy-care/file-management/add/index")),
    "/fubao/pre-pregnancy-care/file-management/edit":lazy(() => import("../pages/fubao/pre-pregnancy-care/file-management/edit/index")),
    "/fubao/pre-pregnancy-care/file-management":lazy(() => import("../pages/fubao/pre-pregnancy-care/file-management/index")),
    "/fubao/pre-pregnancy-care/husband/husband-exam":lazy(() => import("../pages/fubao/pre-pregnancy-care/husband/husband-exam/index")),
    "/fubao/pre-pregnancy-care/wife/wife-exam":lazy(() => import("../pages/fubao/pre-pregnancy-care/wife/wife-exam/index")),
    "/fubao/premarital-care/file-management/add":lazy(() => import("../pages/fubao/premarital-care/file-management/add/index")),
    "/fubao/premarital-care/file-management/edit":lazy(() => import("../pages/fubao/premarital-care/file-management/edit/index")),
    "/fubao/premarital-care/file-management":lazy(() => import("../pages/fubao/premarital-care/file-management/index")),
    "/fubao/premarital-care/husband-v2/husband-exam":lazy(() => import("../pages/fubao/premarital-care/husband-v2/husband-exam/index")),
    "/fubao/premarital-care/wife-v2/wife-exam":lazy(() => import("../pages/fubao/premarital-care/wife-v2/wife-exam/index")),
}