import { ModelService } from "../../ModelService"
export interface IMchc_Pregnancy {
    admissions: null
    age: null
    auditor: null
    auditorId: null
    auditorName: null
    birthInsurance: null
    birthPermit: null
    branchNO: null
    censusRegister: null
    checkIdNO: null
    closingDate: null
    closingGestationalWeek: null
    closingNote: null
    createdBy: null
    createdDate: "2022-05-05 16:05:46"
    currentGestationalWeek: "--"
    currentSystemTime: "2022-05-05"
    customerService: null
    customerServiceBindDate: null
    customerServiceBindStatus: null
    customerServiceDiag: null
    datasource: null
    deleteFlag: false
    deliveryDate: null
    deliveryGestationalWeek: null
    deliveryMode: null
    deliveryPoint: null
    dob: null
    edd: null
    ethnic: null
    fetalMovements: null
    fetalcount: null
    firstRecord: null
    gender: null
    gravidity: null
    highriskGrade?: string
    highriskNote?: string
    id: 12
    idNO: null
    idType: null
    infection: null
    infectionNote?: string
    inpatientNO: null
    insuranceType: null
    lastModifiedBy: null
    lastModifiedDate: "2022-05-05 16:05:46"
    lastVisitDate: null
    lmp: null
    maritalAge: null
    mpuid: null
    name: null
    outpatientNO: string
    parity: null
    partnerAge: null
    partnerPatientNO: null
    partnerPermanentResidenceAddress: null
    partnerResidenceAddress: null
    payment: null
    paymentDate: null
    periodState: null
    permanentResidenceAddress: null
    phi: null
    pregnancyCase: null
    prenatalVisitPlans: null
    printLetterOfConsent: null
    remark: null
    reviewDate: null
    sureEdd: null
    telephone: null
    triggerType: null
    ultrasoundExams: null
    // 20220822
    prenatalExam: null
    sureEddModify: null
    uploadLog: null

    // 20220914
    checkupNO: "22091104",
    nationality: "中国",
    nativeplace: "广东省",
    maritalStatus: 1,
    nearRelation: false,
    maritalYears: null,
    education: null,
    occupation: "国家公务员",
    workplace: null,
    workPhone: null,
    occupationDetail: null,
    familyIncome: null,
    residenceAddress: "广东省,揭阳市,揭西县&和谐街道,友爱社区居委会,富强小区4栋902",
    postpartumAddress: "广东省,揭阳市,揭西县&和谐街道,友爱社区居委会,富强小区4栋902",
    partnerName: "匡超",
    partnerGender: null,
    partnerDob: "1998-03-14",
    partnerIdType: 1,
    partnerIdNO: "440229199803141795",
    partnerNationality: "中国",
    partnerNativeplace: "广东省",
    partnerEthnic: "汉族",
    partnerTelephone: "13693315592",
    partnerOccupation: "专业技术人员",
    partnerWorkplace: null,
    partnerOccupationDetail: null,
    gestationalWeek: null,
    createDate: null,
    modifyDate: null,
    validateDate: "2022-09-11",
    note: null,
    recordsrc: null,
    recordstate: "1" | "0" | "6",
    spinsterhoodName: null,
    spinsterhoodTelephone: null,
    spinsterhoodRelation: null,
    referrals: [],
    familyHistory: null,
    procedureHistory: null,
    diseaseHistory: null,
    allergyHistory: null,
    partnerProfile: null,
    personalProfile: null,
    menstrualHistory: null,
    transfusionHistory: null,
    pregnancyHistories: [],
    ultrasounds: [],
    riskRecords: [],
    diagnoses: [],
    organization: null,
    bloodPressures: [],
    bloodGlucoses: [],
}

export const SMchc_Pregnancy = new ModelService<IMchc_Pregnancy>({
    n: '/pregnancies',
})