export const mockData = [
  {
    sendTheProjectName: ['感染三项DNA/RNA', '染色体核型'],
    LabExamResult: [
      [
        {
          id: 1232,
          index: 9,
          itemNO: '11A060',
          itemName: '尿酮体(干化学)',
          limit: '阴性(―)',
          state: null,
          result: '阴性(―)',
          unit: null,
          normalLow: null,
          normalHigh: null,
          criticalLow: '',
          criticalHigh: '',
          labexam: {
            id: 665,
            requestDate: '2021-02-04T07:59:59+08:00',
            reportDate: '2021-01-26T10:30:05+08:00',
            suitNO: null,
            suitName: '感染三项DNA/RNA',
            sampleNO: null,
            profileId: null,
            outpatientNO: '2014',
            inpatientNO: null,
            name: null,
            age: null,
            requestDepName: null,
            requestDepNo: null,
            instrument: null,
            requestDoctorName: null,
            reportDoctorName: null,
            diagnosis: '脐血',
          },
        },
        {
          id: 1233,
          index: 55,
          itemNO: '11A10504',
          itemName: '移行上皮(镜检)',
          limit: null,
          state: null,
          result: '阴性(―)',
          unit: null,
          normalLow: null,
          normalHigh: null,
          criticalLow: '',
          criticalHigh: '',
          labexam: {
            id: 665,
            requestDate: '2021-02-04T07:59:59+08:00',
            reportDate: '2021-01-26T10:30:05+08:00',
            suitNO: null,
            suitName: '感染三项DNA/RNA',
            sampleNO: null,
            profileId: null,
            outpatientNO: '2014',
            inpatientNO: null,
            name: null,
            age: null,
            requestDepName: null,
            requestDepNo: null,
            instrument: null,
            requestDoctorName: null,
            reportDoctorName: null,
            diagnosis: '脐血',
          },
        },
        {
          id: 1234,
          index: 12,
          itemNO: '11A100',
          itemName: '尿隐血(干化学)',
          limit: '阴性(―)',
          state: null,
          result: '阳性(┼)',
          unit: null,
          normalLow: null,
          normalHigh: null,
          criticalLow: '',
          criticalHigh: '',
          labexam: {
            id: 665,
            requestDate: '2021-02-04T07:59:59+08:00',
            reportDate: '2021-01-26T10:30:05+08:00',
            suitNO: null,
            suitName: '感染三项DNA/RNA',
            sampleNO: null,
            profileId: null,
            outpatientNO: '2014',
            inpatientNO: null,
            name: null,
            age: null,
            requestDepName: null,
            requestDepNo: null,
            instrument: null,
            requestDoctorName: null,
            reportDoctorName: null,
            diagnosis: '脐血',
          },
        },
        {
          id: 1230,
          index: 101,
          itemNO: '11A10509',
          itemName: '透明管型(镜检)',
          limit: null,
          state: null,
          result: '阴性(―)',
          unit: null,
          normalLow: null,
          normalHigh: null,
          criticalLow: '',
          criticalHigh: '',
          labexam: {
            id: 665,
            requestDate: '2021-02-04T07:59:59+08:00',
            reportDate: '2021-01-26T10:30:05+08:00',
            suitNO: null,
            suitName: '感染三项DNA/RNA',
            sampleNO: null,
            profileId: null,
            outpatientNO: '2014',
            inpatientNO: null,
            name: null,
            age: null,
            requestDepName: null,
            requestDepNo: null,
            instrument: null,
            requestDoctorName: null,
            reportDoctorName: null,
            diagnosis: '脐血',
          },
        },
        {
          id: 1231,
          index: 102,
          itemNO: '11A10554',
          itemName: '颗粒管型(镜检)',
          limit: null,
          state: null,
          result: '阴性(―)',
          unit: null,
          normalLow: null,
          normalHigh: null,
          criticalLow: '',
          criticalHigh: '',
          labexam: {
            id: 665,
            requestDate: '2021-02-04T07:59:59+08:00',
            reportDate: '2021-01-26T10:30:05+08:00',
            suitNO: null,
            suitName: '感染三项DNA/RNA',
            sampleNO: null,
            profileId: null,
            outpatientNO: '2014',
            inpatientNO: null,
            name: null,
            age: null,
            requestDepName: null,
            requestDepNo: null,
            instrument: null,
            requestDoctorName: null,
            reportDoctorName: null,
            diagnosis: '脐血',
          },
        },
      ],
      [
        {
          id: 1227,
          index: 3,
          itemNO: '11A035',
          itemName: 'PH(干化学)',
          limit: '5.0 - 9.0',
          state: null,
          result: '6.0',
          unit: null,
          normalLow: '5',
          normalHigh: '9',
          criticalLow: '',
          criticalHigh: '',
          labexam: {
            id: 664,
            requestDate: '2021-02-04T08:00:00+08:00',
            reportDate: '2021-01-25T08:00:00+08:00',
            suitNO: null,
            suitName: '染色体核型',
            sampleNO: null,
            profileId: null,
            outpatientNO: '2014',
            inpatientNO: null,
            name: null,
            age: null,
            requestDepName: null,
            requestDepNo: null,
            instrument: null,
            requestDoctorName: null,
            reportDoctorName: null,
            diagnosis: '脐血',
          },
        },
        {
          id: 1228,
          index: 52,
          itemNO: '11A10502',
          itemName: '红细胞 (RBC)(镜检)',
          limit: null,
          state: null,
          result: '0-3/HP',
          unit: null,
          normalLow: null,
          normalHigh: null,
          criticalLow: '',
          criticalHigh: '',
          labexam: {
            id: 664,
            requestDate: '2021-02-04T08:00:00+08:00',
            reportDate: '2021-01-25T08:00:00+08:00',
            suitNO: null,
            suitName: '染色体核型',
            sampleNO: null,
            profileId: null,
            outpatientNO: '2014',
            inpatientNO: null,
            name: null,
            age: null,
            requestDepName: null,
            requestDepNo: null,
            instrument: null,
            requestDoctorName: null,
            reportDoctorName: null,
            diagnosis: '脐血',
          },
        },
        {
          id: 1229,
          index: 5,
          itemNO: '11A080',
          itemName: '尿粒细胞酯酶(干化学)',
          limit: '阴性(―)',
          state: null,
          result: '阴性(―)',
          unit: null,
          normalLow: null,
          normalHigh: null,
          criticalLow: '',
          criticalHigh: '',
          labexam: {
            id: 664,
            requestDate: '2021-02-04T08:00:00+08:00',
            reportDate: '2021-01-25T08:00:00+08:00',
            suitNO: null,
            suitName: '染色体核型',
            sampleNO: null,
            profileId: null,
            outpatientNO: '2014',
            inpatientNO: null,
            name: null,
            age: null,
            requestDepName: null,
            requestDepNo: null,
            instrument: null,
            requestDoctorName: null,
            reportDoctorName: null,
            diagnosis: '脐血',
          },
        },
      ],
    ],
    operationName: '胎儿囊液穿刺',
    fetal: 'F4',
    fetalLocation: '上',
    samplesName: '脐血',
  },
  {
    sendTheProjectName: ['地贫筛查组合(Hb电泳)'],
    LabExamResult: [
      [
        {
          id: 1226,
          index: 301,
          itemNO: '11A10540',
          itemName: '真菌(镜检)',
          limit: '未见(―)',
          state: null,
          result: '未见(―)',
          unit: null,
          normalLow: null,
          normalHigh: null,
          criticalLow: '',
          criticalHigh: '',
          labexam: {
            id: 666,
            requestDate: '2021-02-03T00:34:01+08:00',
            reportDate: '2021-01-27T00:33:11+08:00',
            suitNO: null,
            suitName: '地贫筛查组合(Hb电泳)',
            sampleNO: null,
            profileId: null,
            outpatientNO: '2014',
            inpatientNO: null,
            name: null,
            age: null,
            requestDepName: null,
            requestDepNo: null,
            instrument: null,
            requestDoctorName: null,
            reportDoctorName: null,
            diagnosis: '绒毛',
          },
        },
      ],
    ],
    operationName: '胎儿囊液穿刺',
    fetal: 'F1',
    fetalLocation: '右下',
    samplesName: '绒毛',
  },
];
