export default {
  '海外': [
    'Afghanistan阿富汗',
    'Albania阿尔巴尼亚',
    'Algeria阿尔及利亚',
    'AmericanSamoa美属萨摩亚',
    'Angola安道尔',
    'Angola安哥拉',
    'Antigua and Barbuda安提瓜和巴布达',
    'Algeria阿塞拜疆',
    'Argentina阿根廷',
    'Australia澳大利亚',
    'Austria奥地利',
    'Bahamas巴哈马',
    'Bahrain巴林',
    'Bangladesh孟加拉',
    'Armenia亚美尼亚',
    'Barbados巴巴多斯',
    'Belgium比利时',
    'Bermuda百慕大',
    'Bhutan不丹',
    'Bolivia玻利维亚',
    'Bosnia and Herzegovina波黑',
    'Botswana博茨瓦纳',
    'Bouvet Island布韦岛',
    'Brazil巴西',
    'Belize伯利兹',
    'British Indian Ocean Territory英属印度洋领地',
    'Solomon Islands所罗门群岛',
    'The British Virgin Islands英属维尔京群岛',
    'Brunei文莱',
    'Bulgaria保加利亚',
    'Myanmar缅甸',
    'Burundi布隆迪',
    'Belarus白俄罗斯',
    'Cambodia柬埔寨',
    'Cameroon喀麦隆',
    'Canada加拿大',
    'Cape Verde佛得角',
    'Cayman Islands开曼群岛',
    'Central African Republic中非',
    'Sri Lanka斯里兰卡',
    'Chad乍得',
    'Chile智利',
    'Christmas Islands圣诞岛',
    'Cocos (keeling) Islands科科斯群岛',
    'Colombia哥伦比亚',
    'Comoros科摩罗',
    'Mayotte马约特',
    'Congo刚果（布）',
    'Congo(Congo-Kinshasa)刚果（金）',
    'Cook Islands库克群岛',
    'Costa Rica哥斯达黎加',
    'Croatia克罗地亚',
    'Cuba古巴',
    'Cyprus塞浦路斯',
    'Czech捷克',
    'Benin贝宁',
    'Denmark丹麦',
    'Dominica多米尼克',
    'Dominican多米尼加',
    'Ecuador厄瓜多尔',
    'El Salvador萨尔瓦多',
    'Equatorial Guinea赤道几内亚',
    'Ethiopia埃塞俄比亚',
    'Eritrea厄立特里亚',
    'Estonia爱沙尼亚',
    'Faroe Islands法罗群岛',
    'Falkland Islands马尔维纳斯群岛（ 福克兰）',
    'South Georgia and The South Sandwich Islands南乔治亚岛和南桑威奇群岛',
    'Fiji斐济群岛',
    'Finland芬兰',
    'Aland Islands奥兰群岛',
    'France法国',
    'French Guiana法属圭亚那',
    'French Polynesia法属波利尼西亚',
    'French Southern Territories法属南部领地',
    'Djibouti吉布提',
    'Gabon加蓬',
    'Georgia格鲁吉亚',
    'Gambia冈比亚',
    'Palestine巴勒斯坦',
    'Germany德国',
    'Ghana加纳',
    'Gibraltar直布罗陀',
    'Kiribati基里巴斯',
    'Greece希腊',
    'Greenland格陵兰',
    'Grenada格林纳达',
    'Guadeloupe瓜德罗普',
    'Guam关岛',
    'Guatemala危地马拉',
    'Guinea几内亚',
    'Guyana圭亚那',
    'Haiti海地',
    'Heard and McDonald Islands赫德岛和麦克唐纳群岛',
    'Vatican City梵蒂冈',
    'Honduras洪都拉斯',
    'Hungary匈牙利',
    'Iceland冰岛',
    'India印度',
    'Indonesia印尼',
    'Iran伊朗',
    'Iraq伊拉克',
    'Ireland爱尔兰',
    'Israel以色列',
    'Italy意大利',
    "Cote D'Ivoire科特迪瓦",
    'Jamaica牙买加',
    'Japan日本',
    'Kazakhstan哈萨克斯坦',
    'Jordan约旦',
    'Kenya肯尼亚',
    'Korea(North)朝鲜',
    'Korea(South)韩国',
    'Kuwait科威特',
    'Kyrgyzstan吉尔吉斯斯坦',
    'Laos老挝',
    'Lebanon黎巴嫩',
    'Lesotho莱索托',
    'Latvia拉脱维亚',
    'Liberia利比里亚',
    'Libya利比亚',
    'Liechtenstein列支敦士登',
    'Lithuania立陶宛',
    'Luxembourg卢森堡',
    'Madagascar马达加斯加',
    'Malawi马拉维',
    'Malaysia马来西亚',
    'Maldives马尔代夫',
    'Mali马里',
    'Malta马耳他',
    'Martinique马提尼克',
    'Mauritania毛里塔尼亚',
    'Mauritius毛里求斯',
    'Mexico墨西哥',
    'Monaco摩纳哥',
    'Mongolia蒙古国',
    'Moldova摩尔多瓦',
    'Montenegro黑山',
    'Montserrat蒙塞拉特岛',
    'Morocco摩洛哥',
    'Mozambique莫桑比克',
    'Argentina阿曼',
    'Namibia纳米比亚',
    'Nauru瑙鲁',
    'Nepal尼泊尔',
    'Netherlands荷兰',
    'Oman阿鲁巴',
    'Caribisch Nederland荷兰加勒比区',
    'New Caledonia新喀里多尼亚',
    'Aruba瓦努阿图',
    'New Zealand新西兰',
    'Nicaragua尼加拉瓜',
    'Niger尼日尔',
    'Nigeria尼日利亚',
    'Niue纽埃',
    'Norfolk Island诺福克岛',
    'Norway挪威',
    'Northern Mariana Islands北马里亚纳群岛',
    'United States Minor Outlying Islands美国本土外小岛屿',
    'The Federated States of Micronesia密克罗尼西亚联邦',
    'Marshall Islands马绍尔群岛',
    'Palau帕劳',
    'Pakistan巴基斯坦',
    'Panama巴拿马',
    'Papua New Guinea巴布亚新几内亚',
    'Paraguay巴拉圭',
    'Peru秘鲁',
    'Philippines菲律宾',
    'Pitcairn Islands皮特凯恩群岛',
    'Poland波兰',
    'Portugal葡萄牙',
    'Guinea-Bissau几内亚比绍',
    'Timor-Leste东帝汶',
    'Puerto Rico波多黎各',
    'Qatar卡塔尔',
    'Reunion留尼汪',
    'Romania罗马尼亚',
    'Russian Federation俄罗斯',
    'Rwanda卢旺达',
    'Saint Barthelemy圣巴泰勒米岛',
    'Saint Helena圣赫勒拿',
    'Saint Kitts-Nevis圣基茨和尼维斯',
    'Anguilla安圭拉',
    'Saint Lucia圣卢西亚',
    'Saint-Martin法属圣马丁',
    'The Islands of st pierre and miquelon圣皮埃尔和密克隆',
    'Saint Vincent and the Grenadines圣文森特和格林纳丁斯',
    'San Marino圣马力诺',
    'Sao Tome and Principe圣多美和普林西比',
    'Saudi Arabia沙特阿拉伯',
    'Senegal塞内加尔',
    'Serbia塞尔维亚',
    'Seychelles塞舌尔',
    'Sierra Leone塞拉利昂',
    'Singapore新加坡',
    'Slovakia斯洛伐克',
    'Vietnam越南',
    'Slovenia斯洛文尼亚',
    'Somalia索马里',
    'South Africa南非',
    'Zimbabwe津巴布韦',
    'Spain西班牙',
    'South Sudan南苏丹',
    'Sudan苏丹',
    'Western Sahara西撒哈拉',
    'Suriname苏里南',
    'SvalbardogJanMayen斯瓦尔巴群岛和扬马延岛',
    'Swaziland斯威士兰',
    'Sweden瑞典',
    'Switzerland瑞士',
    'Syria叙利亚',
    'Tajikistan塔吉克斯坦',
    'Thailand泰国',
    'Togo多哥',
    'Tokelau托克劳',
    'Tonga汤加',
    'Trinidad and Tobago特立尼达和多巴哥',
    'Tunisia突尼斯',
    'Turkey土耳其',
    'Turkmenistan土库曼斯坦',
    'Turks and Caicos Islands特克斯和凯科斯群岛',
    'Tuvalu图瓦卢',
    'United ArabEmirates阿联酋',
    'Uganda乌干达',
    'Ukraine乌克兰',
    'Macedonia马其顿',
    'Egypt埃及',
    'United Kingdom英国',
    'Guernsey根西岛',
    'Jersey泽西岛',
    'Isle of Man马恩岛',
    'Tanzania坦桑尼亚',
    'United States美国',
    'Virgin Islands of the UnitedStates美属维尔京群岛',
    'Burkina Faso布基纳法索',
    'Uruguay乌拉圭',
    'Uzbekistan乌兹别克斯坦',
    'Venezuela委内瑞拉',
    'Wallis and Futuna瓦利斯和富图纳',
    'Samoa萨摩亚',
    'Yemen也门',
    'Zambia赞比亚'
  ]
}
