export const freeAllowance = {
  1: {
    account: '地贫复筛（血红蛋白成分分析）',
    province: 22.9,
    city: 7.6,
    county: 7.6,
  },
  2: {
    account: '地贫基因检测',
    province: 310.2,
    city: 103.4,
    county: 103.4,
  },
  3: {
    account: '孕早期血清学唐氏筛查',
    province: 70.2,
    city: 23.4,
    county: 23.4,
  },
  4: {
    account: '孕中期血清学唐氏筛查',
    province: 79.6,
    city: 26.55,
    county: 26.55,
  },
  5: {
    account: '孕妇外周血游离DNA产前筛查（NIPT）',
    province: 360,
    city: 120,
    county: 120,
  },
  6: {
    account: '孕早期严重致死残致残性结构畸形超声筛查（含NT）',
    province: 95.6,
    city: 31.85,
    county: 31.85,
  },
  7: {
    account: '严重致死残致残性结构畸形超声筛查',
    province: 95.6,
    city: 31.85,
    county: 31.85,
  },
  8: {
    account: '地贫',
    province: 1110,
    city: 370,
    county: 370,
  },
  9: {
    account: '严重单基因病',
    province: 1110,
    city: 370,
    county: 370,
  },
  10: {
    account: '致死残致残性染色体病',
    province: 1110,
    city: 370,
    county: 370,
  },
  11: {
    account: '致死残致残性结构畸形',
    province: 1110,
    city: 370,
    county: 370,
  },
  12: {
    account: '新生儿遗传代谢病（初筛）',
    province: 61.1,
    city: 20.4,
    county: 20.4,
  },
  13: {
    account: '新生儿甲状腺功能减低症（复筛）',
    province: 68.9,
    city: 22.95,
    county: 22.95,
  },
  14: {
    account: '新生儿苯丙酮尿症（复筛）',
    province: 130.6,
    city: 43.5,
    county: 43.5,
  },
  15: {
    account: '新生儿G6pd缺乏症（复筛）',
    province: 5,
    city: 1.65,
    county: 1.65,
  },
  16: {
    account: '新生儿先天性肾上腺皮质增多症（复筛）',
    province: 58.1,
    city: 19.35,
    county: 19.35,
  },
  17: {
    account: '新生儿听力筛查（初筛）',
    province: 45.5,
    city: 15.15,
    county: 15.15,
  },
  18: {
    account: '新生儿听力筛查（复筛）',
    province: 161.7,
    city: 53.95,
    county: 53.95,
  },
  19: {
    account: '早产儿视网膜病变（初筛）',
    province: 174.4,
    city: 58.15,
    county: 58.15,
  },
  20: {
    account: '早产儿视网膜病变（复筛）',
    province: 174.4,
    city: 58.15,
    county: 58.15,
  },
  21: {
    account: 'HIV+梅毒+乙肝筛查（免费）',
    province: 0,
    city: 0,
    county: 0,
  },
};

export const allowanceAccount = [
  {
    label: '地贫',
    value: '地贫',
    disabled: true,
    children: [
      { label: '复筛（血红蛋白成分分析）', value: 1 },
      { label: '地贫基因检测', value: 2 },
    ],
  },
  {
    label: '孕期筛查',
    value: '孕期筛查',
    disabled: true,
    children: [
      { label: '孕早期血清学唐氏筛查', value: 3 },
      { label: '孕中期血清学唐氏筛查', value: 4 },
      { label: '孕妇外周血游离DNA产前筛查（NIPT）', value: 5 },
      { label: '孕早期严重致死残致残性结构畸形超声筛查（含NT）', value: 6 },
      { label: '严重致死残致残性结构畸形超声筛查', value: 7 },
    ],
  },
  {
    label: '产前诊断',
    value: '产前诊断',
    disabled: true,
    children: [
      { label: '地贫', value: 8 },
      { label: '严重单基因病', value: 9 },
      { label: '致死残致残性染色体病', value: 10 },
      { label: '致死残致残性结构畸形', value: 11 },
    ],
  },
  {
    label: '疾病筛查',
    value: '疾病筛查',
    disabled: true,
    children: [
      { label: '新生儿遗传代谢病（初筛）', value: 12 },
      { label: '新生儿甲状腺功能减低症（复筛）', value: 13 },
      { label: '新生儿苯丙酮尿症（复筛）', value: 14 },
      { label: '新生儿G6pd缺乏症（复筛）', value: 15 },
      { label: '新生儿先天性肾上腺皮质增多症（复筛）', value: 16 },
      { label: '新生儿听力筛查（初筛）', value: 17 },
      { label: '新生儿听力筛查（复筛）', value: 18 },
      { label: '早产儿视网膜病变（初筛）', value: 19 },
      { label: '早产儿视网膜病变（复筛）', value: 20 },
    ],
  },
  {
    label: '传染病',
    value: '传染病',
    disabled: true,
    children: [{ label: 'HIV+梅毒+乙肝筛查（免费）', value: 21 }],
  },
];
