export const mockData = {
  pdProcedures: [
    {
      object: 1,
      startTime: '14:33',
      endTime: '18:22',
      invasiveNote: {},
    },
  ],
  pdPreBloodFlows: [
    {
      id: 12,
      checkDate: '2020-07-14',
      uaEdf: '23',
      uaPi: '3',
      uaRi: '2',
      uaSdratio: '2',
      mcaPsv: '2',
      mcaPi: '2',
      mcaRi: '21',
      mcaSdratio: '2',
      dv: '2',
      note: null,
    },
  ],
  pdPostBloodFlows: [
    {
      id: 9,
      checkDate: '2020-07-06',
      uaEdf: '1',
      uaPi: '2',
      uaRi: '2',
      uaSdratio: '2',
      mcaPsv: '2332',
      mcaPi: '4',
      mcaRi: '88',
      mcaSdratio: '55',
      dv: '23',
      note: null,
    },
  ],
  pdPreHemogram: [
    {
      id: 16,
      rbc: '1',
      hgb: '1',
      wbc: '8',
      hct: '1',
      plt: '1',
      nrbc: '1',
      ret: '1',
      bilirubin: null,
      coombs: '1',
    },
  ],
  pdPostHemogram: [
    {
      id: 8,
      rbc: '5',
      hgb: '5',
      wbc: '5',
      hct: '5',
      plt: '5',
      nrbc: '5',
      ret: '5',
      bilirubin: null,
      coombs: '5',
    },
  ],
  pdPreHemogramBank: [
    {
      id: 1,
      rbc: '3',
      hgb: '3',
      wbc: '3',
      hct: '3',
      plt: '3',
      nrbc: '3',
      bilirubin: '22',
      ret: '3',
      coombs: '33',
    },
  ],
};
