export interface IMchc_Admission_predeliveryDocument {
    "id" : 92,
    "recordDate" : string,
    "recordTime" : "2022-12-02 15:58",
    "temperature" : null,
    "heartrate" : null,
    "pulse" : null,
    "breath" : null,
    "systolic" : null,
    "diastolic" : null,
    "bp" : "[122,22]",
    "os" : null,
    "consciousness" : null,
    "fetalhart" : null,
    "fetalhart2" : null,
    "fetalhart3" : null,
    "amnioticfluidcharacter" : null,
    "fetalPostion" : null,
    "fetalmovement" : null,
    "ucPeriod" : null,
    "ucGap" : null,
    "uc" : null,
    "dilatation" : null,
    "presentation" : -5,
    "takeinType" : null,
    "takeinVolume" : null,
    "outputType" : null,
    "outputVolume" : null,
    "specialNote" : null,
    "recorder" : "士大夫",
    "fetalPosition" : null,
    "amnioticFluid" : null,
    "fetalhartPostion" : null,
    "fetalhartCount" : null,
    "outputColor" : null,
    "ys" : null
}