export interface IMchc_Admission_neonateCareDocument {
    "id": 40,
    "recordDate": string,
    "recordTime": "2022-12-17 11:28:47",
    "temperature": 22.0,
    "heartRate": null,
    "pluse": null,
    "face": null,
    "weep": null,
    "suck": null,
    "haematomas": "[\"2\",\"2\",\"2\"]",
    "complexion": null,
    "breathing": null,
    "response": null,
    "emesis": null,
    "umbilicalcord": null,
    "umbilicus": null,
    "hips": null,
    "feces": null,
    "pee": null,
    "bloodGlucose": null,
    "skinBilirubin": null,
    "feed": null,
    "idBand": null,
    "other": null,
    "recorder": null
}