export interface IMchc_Admission_postnatalCareRecord {
    "id": 122,
    "date": "2022-12-02 15:59:00",
    "recordTime": "2022-12-02 15:59:00",
    "temperature": null,
    "heartrate": null,
    "respiratory": null,
    "bp": "[122,23]",
    "os": null,
    "awareness": null,
    "incomingContent": null,
    "incomingML": null,
    "outcomingContent": null,
    "outcomingML": null,
    "outcomingColor": null,
    "breastCondition": null,
    "lactation": null,
    "woundAbdomen": null,
    "woundPerineum": null,
    "uterineContractions": null,
    "fundalHeight": null,
    "specialSituationRecord": null,
    "nurseSignature": "士大夫"
}