export interface IMchc_Admission_labourStageRecordDocument {
    "id": 105,
    "checktime": "2022-12-02 16:01:20",
    "recordTime": "2022-12-02 16:01:20",
    "temperature": 1.0,
    "pulse": null,
    "respiratory": null,
    "diastolic": 56,
    "systolic": 120,
    "bloodOxygen": null,
    "fetal1heartrate": null,
    "fetal2heartrate": null,
    "fetal3heartrate": null,
    "fetal4heartrate": null,
    "fetal5heartrate": null,
    "fetal6heartrate": null,
    "ucPeriod": null,
    "ucGap": null,
    "uc": null,
    "ucIntensity": null,
    "ucDilatation": null,
    "presentation": null,
    "fetalPosition": null,
    "membraneRuptureType": null,
    "amnioticfluidcharacter": null,
    "hemorrhage": null,
    "urinevolume": null,
    "dosage": null,
    "diet": null,
    "oxytocin": null,
    "specialNote": null,
    "recorder": "士大夫5"
}