export interface IMchc_Admission_tireDischargeRecord {
    "id": 65,
    "inducedAbortionCertificate": null,
    "tireExclusionReason": null,
    "tireExclusionReasonNote": null,
    "inductionMethod": null,
    "inductionMethodNote": null,
    "inductionMethodNote1": null,
    "schedulingMethod": null,
    "schedulingMethodNote": null,
    "schedulingTime": "",
    "placentaDeliveryTime": "",
    "placentaDeliveryMethod": null,
    "perinealConditions": null,
    "perinealConditionsNote": null,
    "placentaIntact": null,
    "intactFetalMembranes": null,
    "qingPalace": null,
    "bleeding": null,
    "bleedingTotal": null,
    "gravidity": 2,
    "parity": 1,
    "gestationalWeek": null,
    "diagnoses": {
        "createdBy": "kevin",
        "createdDate": "2022-12-11 13:33:57",
        "lastModifiedBy": "kevin",
        "lastModifiedDate": "2022-12-11 13:33:57",
        "remark": null,
        "id": 4252,
        "sort": 1,
        "highrisk": null,
        "diagnosis": "病人决定不进行免疫",
        "diagnosisCode": "Z28.201",
        "categoryCode": null,
        "categoryName": null,
        "icdCode": null,
        "note": null,
        "preNote": null,
        "createDate": "2022-12-11",
        "gestationalWeek": null,
        "doctor": null,
        "ignoreState": null,
        "deleted": null,
        "deletedoctor": null,
        "deleteDate": null,
        "visitNo": null,
        "depCode": null,
        "visitTimes": null,
        "pregnancy": null

    }[],
    "diagnosesStr": "",
    "notes": null,
    "palacCleaner": null,
    "observer": null,
    "qualityController": null,
    "uterineRupture": null,
    "infection": null,
    "perineumlaceration": null,
    "perineumNote": null,
    "perineumsutureNote": null,
    "fetusRecords": {
        "id": 48,
        "gender": 3,
        "weight": 22,
        "bodyLength": null,
        "deformity": null
    }[]
}