export interface IMchc_Admission_urinaryRetentionDocument {
    "id" : 99,
    "recordDateTime" : "2022-12-02 16:39:00",
    "recordTime" : "2022-12-02 16:39:00",
    "painFeel" : null,
    "urineFeel" : null,
    "urineTime" : null,
    "bladderFill" : null,
    "urineResidue" : null,
    "opinion" : null,
    "measures_ZDYSZPN" : null,
    "measures_TGYBDPNHJ" : null,
    "measures_JLYDLXL" : null,
    "measures_HJJZJLQX" : null,
    "measures_TLSSHWSCXHY" : null,
    "measures_RFJAMPGQ" : null,
    "measures_RQXZHYBHZP" : null,
    "measures_PGQLL" : null,
    "measures_KSLSGLF" : null,
    "measures_XSDM" : null,
    "measures_WSSB1" : null,
    "measures_DNLZNG" : null,
    "responsibleSign" : "aa",
    "auditorSign" : "士大夫"
}