export interface IMchc_Admission_oxytocinRecordDocument {
    "id" : 4,
    "recordDate" : string,
    "recordTime" : "2022-12-02 16:00",
    "concentration" : null,
    "cerShrinkConcentration" : null,
    "cerShrinkConcentration1" : null,
    "dosage" : null,
    "pluse" : null,
    "speed" : null,
    "speedH" : null,
    "intensity" : null,
    "cerShrinkIntensity" : null,
    "cerShrinkPersist" : null,
    "cerShrinkCycle" : null,
    "fetalHeart" : null,
    "fetalHeart2" : null,
    "fetalHeart3" : null,
    "cervixDilatation" : null,
    "fetalPresentationPosition" : null,
    "systolicPressure" : null,
    "diastolicPressure" : null,
    "specialNote" : "2234",
    "recorder" : "kevinxx",
    "bp" : "[120,66]",
    "concentration1" : null,
    "concentration2" : null,
    "speed1" : null,
    "speed2" : null,
    "uc" : null
}